# Generated by Django 4.2.7 on 2026-08-27 15:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0019_alter_ghlauthcredentials_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneStepGPSIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key', models.TextField(blank=True, default='')),
                ('is_enabled', models.BooleanField(default=True)),
                ('webhook_username', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_password', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onestepgps_integration', to='accounts.ghlauthcredentials')),
            ],
            options={
                'db_table': 'onestepgps_integration',
            },
        ),
    ]
