# Generated by Django 4.2.7 on 2026-08-27 17:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_ghlauthcredentials_user_id'),
        ('onestepgps_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneStepGPSAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_alert_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('alert_name', models.CharField(blank=True, default='', max_length=255)),
                ('alert_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('device_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('device_name', models.CharField(blank=True, default='', max_length=255)),
                ('drive_status', models.CharField(blank=True, default='', max_length=255)),
                ('drive_status_duration_seconds', models.FloatField(blank=True, null=True)),
                ('ignition_on', models.BooleanField(blank=True, null=True)),
                ('speed_mph', models.FloatField(blank=True, null=True)),
                ('posted_speed_limit_mph', models.FloatField(blank=True, null=True)),
                ('odometer', models.FloatField(blank=True, null=True)),
                ('external_voltage', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_raw', models.CharField(blank=True, default='', max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onestepgps_alerts', to='accounts.ghlauthcredentials')),
            ],
            options={
                'db_table': 'onestepgps_alert',
                'ordering': ['-alert_time', '-created_at'],
                'indexes': [models.Index(fields=['account', '-alert_time'], name='onestepgps__account_fc0b46_idx'), models.Index(fields=['account', 'alert_name', '-alert_time'], name='onestepgps__account_4d2e6b_idx'), models.Index(fields=['account', 'external_alert_id'], name='onestepgps__account_3ef734_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='onestepgpsalert',
            constraint=models.UniqueConstraint(condition=models.Q(('external_alert_id', ''), _negated=True), fields=('account', 'external_alert_id'), name='onestepgps_alert_account_external_uniq'),
        ),
    ]
