# Generated by Django 4.2.7 on 2026-09-08 14:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_ghlauthcredentials_user_id'),
        ('onestepgps_app', '0004_onestepgpsintegration_last_webhook_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='onestepgpsmaintenance',
            name='interval_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onestepgpsmaintenance',
            name='interval_miles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onestepgpsmaintenance',
            name='last_service_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onestepgpsmaintenance',
            name='last_service_miles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onestepgpsmaintenance',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='onestepgpsmaintenance',
            name='schedule_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onestepgpsmaintenance',
            name='service_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='OneStepGPSServiceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255)),
                ('device_name', models.CharField(blank=True, default='', max_length=255)),
                ('service_type', models.CharField(blank=True, default='service', max_length=64)),
                ('performed_at', models.DateTimeField()),
                ('odometer_miles', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onestepgps_service_logs', to='accounts.ghlauthcredentials')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='onestepgps_app.onestepgpsmaintenance')),
            ],
            options={
                'db_table': 'onestepgps_service_log',
                'ordering': ['-performed_at', '-created_at'],
            },
        ),
    ]
