# Generated by Django 4.2.7 on 2025-11-21 20:03

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobtracker_app', '0010_alter_job_status_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_time_bonus_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Bonus for the quoted-by employee on first-time projects', max_digits=5)),
                ('quoted_by_bonus_percentage', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Bonus for the quoted-by employee on regular (non-first-time) projects', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payroll Settings',
                'verbose_name_plural': 'Payroll Settings',
                'db_table': 'payroll_settings',
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated automatically on check-out', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='checked_in', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'time_entries',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('timezone', models.CharField(default='America/Chicago', max_length=50)),
                ('pay_scale_type', models.CharField(choices=[('hourly', 'Hourly'), ('project', 'Project')], max_length=20)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text="Required if pay_scale_type is 'hourly'", max_digits=10, null=True)),
                ('is_administrator', models.BooleanField(default=False, help_text='Grants access to view stats, edit records, and manage time entries')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_type', models.CharField(choices=[('hourly', 'Hourly'), ('project', 'Project'), ('bonus_first_time', 'First Time Bonus'), ('bonus_quoted_by', 'Quoted By Bonus')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('project_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('project_title', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='jobtracker_app.job')),
                ('time_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='payroll_app.timeentry')),
            ],
            options={
                'db_table': 'payouts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', '-created_at'], name='payouts_employe_67f9f6_idx'), models.Index(fields=['job', 'employee'], name='payouts_job_id_d526fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='CollaborationRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_count', models.PositiveIntegerField(help_text='Number of team members (1=solo, 2=two members, etc.)')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage rate for this team size', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaboration_rates',
                'ordering': ['employee', 'member_count'],
                'unique_together': {('employee', 'member_count')},
            },
        ),
    ]
