# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='source',
            field=models.CharField(
                blank=True,
                choices=[('auto', 'Auto'), ('manual', 'Manual')],
                default='auto',
                max_length=10,
                null=True
            ),
        ),
    ]

