# Generated by Django 4.2.7 on 2026-03-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0004_payroll_multi_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='payout_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('project', 'Project'), ('bonus_first_time', 'First Time Bonus'), ('bonus_quoted_by', 'Quoted By Bonus'), ('tip', 'Tip')], max_length=20),
        ),
    ]
