# Generated by Django 4.2.7 on 2026-08-20 13:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0019_alter_ghlauthcredentials_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('reward_mode', models.CharField(choices=[('two_sided', 'Both people'), ('referrer_only', 'Referrer only'), ('friend_only', 'New customer only')], default='two_sided', max_length=20)),
                ('referrer_reward_cents', models.PositiveIntegerField(default=2500)),
                ('friend_reward_cents', models.PositiveIntegerField(default=2500)),
                ('minimum_invoice_cents', models.PositiveIntegerField(default=10000)),
                ('monthly_referrer_cap_cents', models.PositiveIntegerField(default=25000)),
                ('invitation_trigger', models.CharField(choices=[('completed_job', 'Job completed'), ('review_clicked', 'Review clicked'), ('five_star_review', 'Five-star review'), ('either', 'Job completed or five-star review')], default='completed_job', max_length=32)),
                ('auto_invite_enabled', models.BooleanField(default=True)),
                ('email_invite_enabled', models.BooleanField(default=True)),
                ('sms_invite_enabled', models.BooleanField(default=True)),
                ('email_delay_minutes', models.PositiveIntegerField(default=60)),
                ('sms_delay_minutes', models.PositiveIntegerField(default=5)),
                ('email_cadence', models.CharField(choices=[('once', 'One time only'), ('quarterly', 'Every 3 months'), ('semiannual', 'Every 6 months'), ('annual', 'Every year')], default='once', max_length=20)),
                ('sms_cadence', models.CharField(choices=[('once', 'One time only'), ('quarterly', 'Every 3 months'), ('semiannual', 'Every 6 months'), ('annual', 'Every year')], default='once', max_length=20)),
                ('primary_color', models.CharField(default='#1472e8', max_length=16)),
                ('accent_color', models.CharField(default='#0c4fac', max_length=16)),
                ('service_label', models.CharField(default='home service', max_length=80)),
                ('terms_text', models.TextField(default='Credits are issued after the referred customer completes and pays for an eligible first invoice. Existing customers, duplicates, and self-referrals do not qualify. Credits have no cash value, cannot be transferred, and are subject to the monthly referrer cap. Credits auto-apply to a future invoice.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_program', to='accounts.ghlauthcredentials')),
            ],
            options={
                'db_table': 'referral_programs',
            },
        ),
        migrations.CreateModel(
            name='ReferralProcessedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=160)),
                ('event_type', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_processed_events', to='accounts.ghlauthcredentials')),
            ],
            options={
                'db_table': 'referral_processed_events',
            },
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='accounts.ghlauthcredentials')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='accounts.contact')),
            ],
            options={
                'db_table': 'referral_links',
            },
        ),
        migrations.CreateModel(
            name='ReferralAttribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_code', models.CharField(max_length=32)),
                ('referred_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('qualified', 'Qualified'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=16)),
                ('source', models.CharField(default='share_link', max_length=32)),
                ('quote_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('qualifying_job_id', models.UUIDField(blank=True, null=True)),
                ('qualifying_invoice_id', models.CharField(blank=True, default='', max_length=100)),
                ('qualifying_invoice_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_attributions', to='accounts.ghlauthcredentials')),
                ('referred_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_attributions', to='accounts.contact')),
                ('referrer_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='accounts.contact')),
            ],
            options={
                'db_table': 'referral_attributions',
            },
        ),
        migrations.CreateModel(
            name='CustomerCreditLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('referrer_reward', 'Referrer reward'), ('friend_reward', 'Friend reward'), ('application', 'Invoice application'), ('release', 'Released reservation'), ('reversal', 'Reversal'), ('manual_adjustment', 'Manual adjustment')], max_length=32)),
                ('amount_cents', models.IntegerField(help_text='Signed integer cents. Positive credits the customer.')),
                ('balance_after_cents', models.IntegerField()),
                ('invoice_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('job_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_credit_ledger', to='accounts.ghlauthcredentials')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledger', to='accounts.contact')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='referral_app.referralattribution')),
            ],
            options={
                'db_table': 'customer_credit_ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='referralprocessedevent',
            constraint=models.UniqueConstraint(fields=('account', 'event_id'), name='uniq_referral_processed_event_account_event'),
        ),
        migrations.AddIndex(
            model_name='referrallink',
            index=models.Index(fields=['account', 'code'], name='referral_li_account_704068_idx'),
        ),
        migrations.AddConstraint(
            model_name='referrallink',
            constraint=models.UniqueConstraint(fields=('account', 'contact'), name='uniq_referral_link_account_contact'),
        ),
        migrations.AddIndex(
            model_name='referralattribution',
            index=models.Index(fields=['account', 'status', 'created_at'], name='referral_at_account_cbd2b4_idx'),
        ),
        migrations.AddIndex(
            model_name='referralattribution',
            index=models.Index(fields=['referrer_contact', 'status'], name='referral_at_referre_4ec516_idx'),
        ),
        migrations.AddIndex(
            model_name='referralattribution',
            index=models.Index(fields=['account', 'referred_email'], name='referral_at_account_b91ada_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralattribution',
            constraint=models.UniqueConstraint(fields=('account', 'referred_contact'), name='uniq_referral_account_referred_contact'),
        ),
        migrations.AddIndex(
            model_name='customercreditledger',
            index=models.Index(fields=['account', 'contact', 'created_at'], name='customer_cr_account_bab317_idx'),
        ),
        migrations.AddIndex(
            model_name='customercreditledger',
            index=models.Index(fields=['account', 'created_at'], name='customer_cr_account_5424c0_idx'),
        ),
        migrations.AddIndex(
            model_name='customercreditledger',
            index=models.Index(fields=['invoice_id'], name='customer_cr_invoice_2d3646_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercreditledger',
            constraint=models.UniqueConstraint(fields=('account', 'idempotency_key'), name='uniq_credit_ledger_account_idempotency'),
        ),
    ]
