# Generated by Django 4.2.7 on 2025-11-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='scope',
            field=models.TextField(blank=True, null=True),
        ),
    ]
