# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_ghlauthcredentials_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHLCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Human-readable name of the custom field (e.g., 'Quote URL', 'Invoice URL')", max_length=255)),
                ('ghl_field_id', models.CharField(help_text='The GHL custom field ID used in API calls', max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('url', 'URL'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox')], default='text', help_text='Type of the custom field', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this field is used for', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this custom field mapping is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='The account this custom field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='accounts.ghlauthcredentials')),
            ],
            options={
                'db_table': 'ghl_custom_fields',
                'ordering': ['field_name'],
            },
        ),
        migrations.AddIndex(
            model_name='ghlcustomfield',
            index=models.Index(fields=['account', 'is_active'], name='ghl_custom_account_idx'),
        ),
        migrations.AddIndex(
            model_name='ghlcustomfield',
            index=models.Index(fields=['ghl_field_id'], name='ghl_custom_ghl_fiel_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ghlcustomfield',
            unique_together={('account', 'ghl_field_id')},
        ),
    ]

