# Generated by Django 4.2.7 on 2026-01-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ghlcustomfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghl_calendar_id', models.CharField(help_text='GHL calendar ID', max_length=255, unique=True)),
                ('location_id', models.CharField(help_text='GHL location ID this calendar belongs to', max_length=255)),
                ('name', models.CharField(help_text='Calendar name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Calendar description', null=True)),
                ('widget_type', models.CharField(blank=True, help_text="Widget type (e.g., 'default')", max_length=50, null=True)),
                ('calendar_type', models.CharField(blank=True, help_text="Calendar type (e.g., 'round_robin')", max_length=50, null=True)),
                ('widget_slug', models.CharField(blank=True, help_text='Widget slug for the calendar', max_length=255, null=True)),
                ('group_id', models.CharField(blank=True, help_text='Group ID if calendar belongs to a group', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ghl_calendars',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='ghlcustomfield',
            new_name='ghl_custom__account_bda223_idx',
            old_name='ghl_custom_account_idx',
        ),
        migrations.RenameIndex(
            model_name='ghlcustomfield',
            new_name='ghl_custom__ghl_fie_036e1e_idx',
            old_name='ghl_custom_ghl_fiel_idx',
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['location_id'], name='ghl_calenda_locatio_93443c_idx'),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['ghl_calendar_id'], name='ghl_calenda_ghl_cal_bd8c47_idx'),
        ),
    ]
