# Generated by Django 4.2.7 on 2026-01-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_calendar_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calendar',
            name='ghl_calenda_locatio_93443c_idx',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='location_id',
        ),
        migrations.AddField(
            model_name='calendar',
            name='account',
            field=models.ForeignKey(blank=True, help_text='The GHL account this calendar belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='accounts.ghlauthcredentials'),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['account'], name='ghl_calenda_account_497eb7_idx'),
        ),
    ]
