# Generated by Django 4.2.7 on 2026-01-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_calendar_ghl_calenda_locatio_93443c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='timezone',
            field=models.CharField(blank=True, default='America/Chicago', max_length=100, null=True),
        ),
    ]
