# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ghlauthcredentials_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHLLocationIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(help_text="GHL custom field parent ID (e.g., 'address_0', 'QmYk134LkK2hownvL1sE')", max_length=255)),
                ('order', models.PositiveIntegerField(help_text='Order/position of this location (0, 1, 2, etc.)')),
                ('name', models.CharField(blank=True, help_text='Optional name/description for this location index', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this location index mapping is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='The GHL account this location index belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='location_indices', to='accounts.ghlauthcredentials')),
            ],
            options={
                'db_table': 'ghl_location_indices',
                'ordering': ['account', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='ghllocationindex',
            index=models.Index(fields=['account', 'is_active'], name='ghl_locatio_account_idx'),
        ),
        migrations.AddIndex(
            model_name='ghllocationindex',
            index=models.Index(fields=['account', 'order'], name='ghl_locatio_account_order_idx'),
        ),
        migrations.AddIndex(
            model_name='ghllocationindex',
            index=models.Index(fields=['parent_id'], name='ghl_locatio_parent_i_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ghllocationindex',
            unique_together={('account', 'parent_id')},
        ),
    ]

