# Generated by Django 4.2.7 on 2026-01-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_ghllocationindex'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ghllocationindex',
            new_name='ghl_locatio_account_623249_idx',
            old_name='ghl_locatio_account_idx',
        ),
        migrations.RenameIndex(
            model_name='ghllocationindex',
            new_name='ghl_locatio_account_ad27b8_idx',
            old_name='ghl_locatio_account_order_idx',
        ),
        migrations.RenameIndex(
            model_name='ghllocationindex',
            new_name='ghl_locatio_parent__e6b1a9_idx',
            old_name='ghl_locatio_parent_i_idx',
        ),
    ]
