# Generated by Django 4.2.7 on 2026-01-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_ghl_locatio_account_idx_ghl_locatio_account_623249_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
