# Generated by Django 4.2.7 on 2026-02-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_ghlmediastorage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ghlmediastorage',
            name='accounts_ghlmediastorage_credentials_ghl_id_uniq',
        ),
        migrations.RenameIndex(
            model_name='ghlmediastorage',
            new_name='ghl_media_s_credent_4f1c8a_idx',
            old_name='ghl_media_s_credent_5a0e0d_idx',
        ),
        migrations.RenameIndex(
            model_name='ghlmediastorage',
            new_name='ghl_media_s_ghl_id_7156d0_idx',
            old_name='ghl_media_s_ghl_id_8b2c3d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='ghlmediastorage',
            unique_together={('credentials', 'ghl_id')},
        ),
    ]
