# Generated by Django 4.2.7 on 2026-02-16 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_ghlmediastorage_accounts_ghlmediastorage_credentials_ghl_id_uniq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(blank=True, help_text='GHL account this contact belongs to (for multi-account onboarding)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.ghlauthcredentials'),
        ),
    ]
