# Generated by Django 4.2.7 on 2025-10-30 17:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quote_app', '0018_quoteschedule_appointment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('services', models.JSONField(blank=True, default=list)),
                ('created_by_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='scheduled', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='quote_app.customersubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
