# Generated by Django 4.2.7 on 2025-10-31 14:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker_app', '0002_rename_appointment_date_job_scheduled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_occurrences', to='jobtracker_app.job')),
            ],
        ),
    ]
