# Generated by Django 4.2.7 on 2025-11-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker_app', '0003_joboccurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='series_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='series_sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
