# Generated by Django 4.2.7 on 2025-11-06 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0014_service_hours_service_price'),
        ('jobtracker_app', '0006_migrate_jtservice_to_service'),  # Run data migration first
    ]

    operations = [
        migrations.AlterField(
            model_name='jobserviceitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_app.service'),
        ),
    ]

