# Generated by Django 4.2.7 on 2025-11-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker_app', '0008_remove_jtservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week for weekly recurring jobs (0=Monday, 6=Sunday)', null=True),
        ),
    ]
