# Generated by Django 4.2.7 on 2025-12-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker_app', '0010_alter_job_status_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completion_processed',
            field=models.BooleanField(default=False, help_text='True if webhook/invoice was already sent when job was completed'),
        ),
    ]
