# Generated by Django 4.2.7 on 2025-12-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker_app', '0011_job_completion_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='invoice_url',
            field=models.URLField(blank=True, help_text='Invoice URL from external system (G4IXyj5y49rKinuXbnCA custom field)', max_length=500, null=True),
        ),
    ]

