# Generated by Django 4.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker_app', '0014_jobimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('online_payment', 'Online Payment'), ('other', 'Other')], help_text='Payment method used for this job (only for completed jobs)', max_length=20, null=True),
        ),
    ]

