# Generated by Django 4.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ghlauthcredentials_timezone'),
        ('jobtracker_app', '0015_job_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contact',
            field=models.ForeignKey(
                blank=True,
                help_text='Link to Contact model (optional - if provided, customer info will be populated from this)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='jobs',
                to='accounts.contact'
            ),
        ),
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.ForeignKey(
                blank=True,
                help_text='Link to Address model (optional - if provided, customer_address will be populated from this)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='jobs',
                to='accounts.address'
            ),
        ),
    ]

