# Generated by Django 4.2.7 on 2026-03-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker_app', '0020_job_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('to_convert', 'Needs Conversion'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('service_due', 'Service Due'), ('on_the_way', 'On The Way'), ('in_progress', 'In Progress'), ('onhold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
