# Generated by Django 4.2.7 on 2025-11-25 16:13

from decimal import Decimal
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('alt_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('alt_type', models.CharField(blank=True, max_length=50, null=True)),
                ('company_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('location_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, default='INVOICE', max_length=200, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('payment_processing', 'Payment Processing'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('partial', 'Partial'), ('overdue', 'Overdue'), ('void', 'Void')], db_index=True, default='draft', max_length=30)),
                ('live_mode', models.BooleanField(default=True)),
                ('business_name', models.CharField(blank=True, max_length=300, null=True)),
                ('business_logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('business_address', models.JSONField(blank=True, default=dict)),
                ('business_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('business_website', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=300, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_company_name', models.CharField(blank=True, max_length=300, null=True)),
                ('contact_address', models.JSONField(blank=True, default=dict)),
                ('currency', models.CharField(blank=True, default='USD', max_length=10, null=True)),
                ('currency_symbol', models.CharField(blank=True, default='$', max_length=5, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_type', models.CharField(blank=True, default='fixed', max_length=50, null=True)),
                ('total', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('invoice_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount_paid', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount_due', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('issue_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None)),
                ('sent_to_phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('sent_from_name', models.CharField(blank=True, max_length=300, null=True)),
                ('sent_from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sent_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('terms_notes', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('opportunity_details', models.JSONField(blank=True, default=dict, null=True)),
                ('automatic_taxes_enabled', models.BooleanField(default=False)),
                ('automatic_taxes_calculated', models.BooleanField(default=False)),
                ('payment_schedule', models.JSONField(blank=True, default=dict)),
                ('total_summary', models.JSONField(blank=True, default=dict)),
                ('tips_enabled', models.BooleanField(default=False)),
                ('tips_received', models.JSONField(blank=True, default=list)),
                ('late_fees_enabled', models.BooleanField(default=False)),
                ('late_fees_configuration', models.JSONField(blank=True, default=dict)),
                ('reminders_configuration', models.JSONField(blank=True, default=dict)),
                ('reminders', models.JSONField(blank=True, default=list)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=100)),
                ('product_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('price_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=10, null=True)),
                ('qty', models.DecimalField(decimal_places=4, default=Decimal('1.00'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_inclusive', models.BooleanField(default=False)),
                ('taxes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard_app.invoice')),
            ],
            options={
                'db_table': 'invoice_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['location_id', 'status'], name='invoices_locatio_9d5c28_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['contact_id', 'status'], name='invoices_contact_711396_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date', 'status'], name='invoices_due_dat_4b5593_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-created_at'], name='invoices_created_3daf52_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['item_id'], name='invoice_ite_item_id_7d96df_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['product_id'], name='invoice_ite_product_4c1854_idx'),
        ),
    ]
