# Generated by Django 4.2.7 on 2026-02-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_invoice_account_multi_account'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_account_a3baf6_idx',
            old_name='invoices_account_9a1b2c_idx',
        ),
    ]
