# Generated by Django 4.2.7 on 2025-10-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0012_rename_globalbase_price_globalbaseprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('supervisor', 'Supervisor'), ('worker', 'Worker')], default='worker', max_length=20),
        ),
    ]
