# Generated by Django 4.2.7 on 2025-12-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0014_service_hours_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ghl_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
