# Generated by Django 4.2.7 on 2025-12-09 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_ghlauthcredentials_scope'),
        ('service_app', '0015_user_ghl_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ghl_appointment_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('location_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.URLField(blank=True, help_text='Meeting URL or address', max_length=500, null=True)),
                ('calendar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('appointment_status', models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ghl_contact_id', models.CharField(blank=True, help_text='GHL contact ID', max_length=255, null=True)),
                ('group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ghl_assigned_user_id', models.CharField(blank=True, help_text='GHL assigned user ID', max_length=255, null=True)),
                ('users_ghl_ids', models.JSONField(blank=True, default=list, help_text='Store GHL user IDs from users array')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL, to_field='ghl_user_id')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='accounts.contact', to_field='contact_id')),
                ('users', models.ManyToManyField(blank=True, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-start_time', '-created_at'],
                'indexes': [models.Index(fields=['ghl_appointment_id'], name='appointment_ghl_app_294d09_idx'), models.Index(fields=['location_id'], name='appointment_locatio_24c0c2_idx'), models.Index(fields=['start_time'], name='appointment_start_t_acd4ae_idx')],
            },
        ),
    ]
