# Generated by Django 4.2.7 on 2025-12-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0016_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('showed', 'Showed'), ('noshow', 'No Show'), ('invalid', 'Invalid')], max_length=50, null=True),
        ),
    ]
