# Generated by Django 4.2.7 on 2025-12-09 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker_app', '0013_change_submission_to_foreignkey'),
        ('service_app', '0017_alter_appointment_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_from_backend',
            field=models.BooleanField(default=False, help_text='True if appointment was created from our backend, False if from GHL'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='job',
            field=models.OneToOneField(blank=True, help_text='Related job if appointment was created from a job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='jobtracker_app.job'),
        ),
    ]

