# Generated by Django 4.2.7 on 2026-01-06 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_calendar_ghl_calenda_locatio_93443c_idx_and_more'),
        ('service_app', '0018_add_appointment_backend_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='calendar_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='calendar',
            field=models.ForeignKey(blank=True, help_text='GHL calendar this appointment belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='accounts.calendar'),
        ),
    ]
