# Generated by Django 4.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0019_remove_appointment_calendar_id_appointment_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='estimate_status',
            field=models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('on_my_way', 'On My Way'), ('in_progress', 'In Progress'), ('quoted', 'Quoted'), ('canceled', 'Canceled'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], help_text='Status for estimate appointments (FREE On-Site Estimate calendar)', max_length=50, null=True),
        ),
    ]

