# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_ghlmediastorage'),
        ('service_app', '0020_appointment_estimate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.ForeignKey(
                blank=True,
                help_text='GHL account this user belongs to (for multi-app onboarding)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='users',
                to='accounts.ghlauthcredentials',
            ),
        ),
    ]
