# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0023_appointment_account_globalsizepackage_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagefeature',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
