# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0024_add_packagefeature_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
