# Generated by Django 4.2.7 on 2026-03-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0025_add_feature_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='packagefeature',
            options={'ordering': ['order', 'created_at']},
        ),
    ]
