# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0026_alter_feature_options_alter_packagefeature_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpricing',
            name='yes_pricing_type',
            field=models.CharField(
                choices=[
                    ('upcharge_percent', 'Fixed Upcharge Amount'),
                    ('discount_percent', 'Fixed Discount Amount'),
                    ('upcharge_percent_of_total', 'Upcharge % of Package Total'),
                    ('discount_percent_of_total', 'Discount % of Package Total'),
                    ('fixed_price', 'Fixed Price'),
                    ('ignore', 'Ignore'),
                ],
                default='ignore',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='subquestionpricing',
            name='yes_pricing_type',
            field=models.CharField(
                choices=[
                    ('upcharge_percent', 'Fixed Upcharge Amount'),
                    ('discount_percent', 'Fixed Discount Amount'),
                    ('upcharge_percent_of_total', 'Upcharge % of Package Total'),
                    ('discount_percent_of_total', 'Discount % of Package Total'),
                    ('fixed_price', 'Fixed Price'),
                    ('ignore', 'Ignore'),
                ],
                default='ignore',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='optionpricing',
            name='pricing_type',
            field=models.CharField(
                choices=[
                    ('upcharge_percent', 'Fixed Upcharge Amount'),
                    ('discount_percent', 'Fixed Discount Amount'),
                    ('upcharge_percent_of_total', 'Upcharge % of Package Total'),
                    ('discount_percent_of_total', 'Discount % of Package Total'),
                    ('fixed_price', 'Fixed Price'),
                    ('per_quantity', 'Price Per Quantity'),
                    ('ignore', 'Ignore'),
                ],
                default='ignore',
                max_length=30,
            ),
        ),
    ]
