# Generated by Django 4.2.7 on 2025-01-XX XX:XX

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quote_app', '0021_add_rejected_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSubmissionImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='submission_images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quote_app.customersubmission')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_submission_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Submission Image',
                'verbose_name_plural': 'Customer Submission Images',
                'ordering': ['-created_at'],
                'db_table': 'customer_submission_images',
            },
        ),
    ]
